version: '2.15'
services:
  web:
    image: tamimibnaman/sit323_737-2023-t1-prac7c
    ports:
      - 8080:8080
    restart: always
    healthcheck:
     test: "curl -f localhost:8080"
     interval: 60s
     retries: 10
     start_period: 20s
     timeout: 10s